//= require 'app'
//= require 'directives/remove_error_class'
//= require 'directives/scroll'
//= require 'directives/switch_mobile_menu'
//= require 'controllers/submit_contact_form_controller'
//= require 'controllers/header_controller'
//= require 'services/submit_contact_form_factory'